org: studentkasia
app: memo
service: memo-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: arn:aws:iam::796973483684:role/LambdaDynamoDbRole
  httpApi:
    cors: true
  
    
functions:
  GetMessages:
    handler: functions/GetMessages/index.handler
    events:
      - httpApi:
          path: /api/messages
          method: get
  CreateMessage:
    handler: functions/CreateMessage/index.handler
    events:
      - httpApi:
          path: /api/messages
          method: post
  UpdateMessage:
    handler: functions/UpdateMessage/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: put
  GetSpecMessage:
    handler: functions/GetSpecMessage/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: get        
  DeleteMessages:
    handler: functions/DeleteMessage/index.handler
    events:
      - httpApi:
          path: /api/messages/{id}
          method: delete   
    
resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Messages
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST                  